//
export const AT_SET_MEDIA_SORT_BY = 'AT_SET_MEDIA_SORT_BY';
export const AT_SET_MEDIA_VIEW_BY = 'AT_SET_MEDIA_VIEW_BY';
export const AT_SET_MEDIA_SEARCH_VALUE = 'AT_SET_MEDIA_SEARCH_VALUE';
export const AT_SET_MEDIA_LIST_BY_SORT_BY = 'AT_SET_MEDIA_LIST_BY_SORT_BY';
export const AT_SET_MEDIA_SELECTED_LIST = 'AT_SET_MEDIA_SELECTED_LIST';
export const AT_SET_IS_REFRESH_AFTER_UPDATE = 'AT_SET_IS_REFRESH_AFTER_UPDATE';
export const AT_SET_IS_ACTION_LOADING = 'AT_SET_IS_ACTION_LOADING';

//
export const AT_SET_ADS_MANAGER_KEY_TAB_LIST = 'AT_SET_ADS_MANAGER_KEY_TAB_LIST';
export const AT_SET_ADS_MANAGER_IS_GROUP_PLATFORMS = 'AT_SET_ADS_MANAGER_IS_GROUP_PLATFORMS';
export const AT_SET_ADS_MANAGER_VIEW_BY = 'AT_SET_ADS_MANAGER_VIEW_BY';
export const AT_SET_ADS_MANAGER_FILTER_BY_START_DATE = 'AT_SET_ADS_MANAGER_FILTER_BY_START_DATE';
export const AT_SET_ADS_MANAGER_FILTER_BY_END_DATE = 'AT_SET_ADS_MANAGER_FILTER_BY_END_DATE';
export const AT_SET_ADS_MANAGER_CAMPAIGN_SELECTED_LIST = 'AT_SET_ADS_MANAGER_CAMPAIGN_SELECTED_LIST';
export const AT_SET_ADS_MANAGER_AD_SET_SELECTED_LIST = 'AT_SET_ADS_MANAGER_AD_SET_SELECTED_LIST';
export const AT_SET_ADS_MANAGER_ADS_SELECTED_LIST = 'AT_SET_ADS_MANAGER_ADS_SELECTED_LIST';
export const AT_SET_ADS_MANAGER_ADS_CAMPAIGN_ID_CURRENT = 'AT_SET_ADS_MANAGER_ADS_CAMPAIGN_ID_CURRENT';
export const AT_SET_ADS_MANAGER_ADS_CAMPAIGN_ITEM_CURRENT = 'AT_SET_ADS_MANAGER_ADS_CAMPAIGN_ITEM_CURRENT';
export const AT_SET_ADS_MANAGER_AD_SET_ITEM_CURRENT = 'AT_SET_ADS_MANAGER_AD_SET_ITEM_CURRENT';
export const AT_SET_ADS_MANAGER_ADS_AD_SET_ID_CURRENT = 'AT_SET_ADS_MANAGER_ADS_AD_SET_ID_CURRENT';
export const AT_SET_ADS_MANAGER_ADS_URL_CURRENT = 'AT_SET_ADS_MANAGER_ADS_URL_CURRENT';
export const AT_SET_ADS_MANAGER_DISPLAY_URL_CURRENT = 'AT_SET_ADS_MANAGER_DISPLAY_URL_CURRENT';
//
export const AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_CREATE_MODAL = 'AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_CREATE_MODAL';
export const AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_CREATE_AND_EDIT_MODAL =
    'AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_CREATE_AND_EDIT_MODAL';
export const AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_FINALIZE_MODAL = 'AT_SET_ADS_MANAGER_IS_VISIBILITY_CAMPAIGN_FINALIZE_MODAL';
export const AT_SET_ADS_MANAGER_IS_VISIBILITY_MEDIA_LIBRARY_MODAL = 'AT_SET_ADS_MANAGER_IS_VISIBILITY_MEDIA_LIBRARY_MODAL';
//
export const AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_CREATE_MODAL = 'AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_CREATE_MODAL';
export const AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_CREATE_AND_EDIT_MODAL = 'AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_CREATE_AND_EDIT_MODAL';
export const AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_FINALIZE_MODAL = 'AT_SET_ADS_MANAGER_IS_SHOW_CAMPAIGN_FINALIZE_MODAL';
export const AT_SET_ADS_MANAGER_IS_SHOW_MEDIA_LIBRARY_MODAL = 'AT_SET_ADS_MANAGER_IS_SHOW_MEDIA_LIBRARY_MODAL';
export const AT_SET_ADS_MANAGER_IS_FROM_CAMPAIGN_CREATE_AND_EDIT_MODAL_TO_MEDIA_LIBRARY_MODAL =
    'AT_SET_ADS_MANAGER_IS_FROM_CAMPAIGN_CREATE_AND_EDIT_MODAL_TO_MEDIA_LIBRARY_MODAL';
//
export const AT_SET_ADS_MANAGER_IS_CREATE_AD_SETS = 'AT_SET_ADS_MANAGER_IS_CREATE_AD_SETS';
//
export const AT_SET_ADS_MANAGER_SEARCH_VALUE = 'AT_SET_ADS_MANAGER_SEARCH_VALUE';
//
export const AT_SET_ADS_MANAGER_IS_CREATE_CAMPAIGN = 'AT_SET_ADS_MANAGER_IS_CREATE_CAMPAIGN';
//
export const AT_SET_ADS_MANAGER_CAMPAIGN_PLATFORM_SELECTED_LIST = 'AT_SET_ADS_MANAGER_CAMPAIGN_PLATFORM_SELECTED_LIST';
export const AT_SET_ADS_MANAGER_AD_SET_PLATFORM_SELECTED_LIST = 'AT_SET_ADS_MANAGER_AD_SET_PLATFORM_SELECTED_LIST';
export const AT_SET_ADS_MANAGER_ADS_PLATFORM_SELECTED_LIST = 'AT_SET_ADS_MANAGER_ADS_PLATFORM_SELECTED_LIST';
//
export const AT_SET_ADS_MANAGER_IS_HIDE_EMPTY_ROWS = 'AT_SET_ADS_MANAGER_IS_HIDE_EMPTY_ROWS';
//
export const AT_SET_ADS_MANAGER_IS_SHOW_TAB_USE_EXISTING_CAMPAIGN = 'AT_SET_ADS_MANAGER_IS_SHOW_TAB_USE_EXISTING_CAMPAIGN';
//
export const AT_SET_ADS_DATA_EDIT_FROM_MODAL = 'AT_SET_ADS_DATA_EDIT_FROM_MODAL';
//
export const AT_SET_IS_REFRESH_BY_USER = 'AT_SET_IS_REFRESH_BY_USER';
