
export const AT_SET_CATEGORY_IMAGE_ID = "AT_SET_CATEGORY_IMAGE_ID";
export const AT_SET_CATEGORY_IMAGE_NAME = "AT_SET_CATEGORY_IMAGE_NAME";
export const AT_SET_IMAGE_LIST_BY_CATEGORY = "AT_SET_IMAGE_LIST_BY_CATEGORY";

export const AT_SET_IMAGE_SELECTED_FOR_EDITOR_LIST = "AT_SET_IMAGE_SELECTED_FOR_EDITOR_LIST";
export const AT_SET_IMAGE_SELECTED_TEMP_LIST = "AT_SET_IMAGE_SELECTED_TEMP_LIST";

export const AT_SET_ORDER = "AT_SET_ORDER";
export const AT_SET_IMAGE1_SELECTED_LIST = "AT_SET_IMAGE1_SELECTED_LIST";
export const AT_SET_IMAGE2_SELECTED_LIST = "AT_SET_IMAGE2_SELECTED_LIST";
// 
export const AT_SET_MEDIA_SORT_BY = "AT_SET_MEDIA_SORT_BY";
export const AT_SET_MEDIA_VIEW_BY = "AT_SET_MEDIA_VIEW_BY";
export const AT_SET_MEDIA_SEARCH_VALUE = "AT_SET_MEDIA_SEARCH_VALUE";
export const AT_SET_MEDIA_LIST_BY_SORT_BY = "AT_SET_MEDIA_LIST_BY_SORT_BY";
export const AT_SET_MEDIA_SELECTED_LIST = "AT_SET_MEDIA_SELECTED_LIST";
export const AT_SET_IS_REFRESH_AFTER_UPDATE = "AT_SET_IS_REFRESH_AFTER_UPDATE";
export const AT_SET_IS_ACTION_LOADING = "AT_SET_IS_ACTION_LOADING";
export const AT_SET_MEDIA_SELECTED_LIST_1 = "AT_SET_MEDIA_SELECTED_LIST_1";